<?php

namespace AppBundle\Repository;

/**
 * chaufferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chaufferRepository extends \Doctrine\ORM\EntityRepository
{
}
