admin_lte :
     routes :
        adminlte_login : fos_user_security_login 
        adminlte_login_check : fos_user_security_check 
        adminlte_registration : fos_user_registration_register 
        adminlte_password_reset : fos_user_res_resetting_resquest